// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfsXOsCTGa_7uz5uXhagn8o8fv1WNa8g',
    appId: '1:767729924107:web:5093c1db3cf5abbaacaf0e',
    messagingSenderId: '767729924107',
    projectId: 'curatech-40df8',
    authDomain: 'curatech-40df8.firebaseapp.com',
    storageBucket: 'curatech-40df8.appspot.com',
    measurementId: 'G-6YGHDSQQ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTvH-tSgnW3A8zMiBoqjCmoC2ZI8JG9I',
    appId: '1:767729924107:android:8eb9715630f397bdacaf0e',
    messagingSenderId: '767729924107',
    projectId: 'curatech-40df8',
    storageBucket: 'curatech-40df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwUoiGDHOAaFnsCQ7aN0d2IKx47EG8Gw',
    appId: '1:767729924107:ios:46f201fb4fc6f313acaf0e',
    messagingSenderId: '767729924107',
    projectId: 'curatech-40df8',
    storageBucket: 'curatech-40df8.appspot.com',
    iosBundleId: 'com.example.curaTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSwUoiGDHOAaFnsCQ7aN0d2IKx47EG8Gw',
    appId: '1:767729924107:ios:2af86f493bd6fab8acaf0e',
    messagingSenderId: '767729924107',
    projectId: 'curatech-40df8',
    storageBucket: 'curatech-40df8.appspot.com',
    iosBundleId: 'com.example.curaTech.RunnerTests',
  );
}
